import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Latent Diffusion Transformer (DiT) for Generative Fashion Designer\n",
    "This notebook uses **Latent Diffusion** combined with a **Vision Transformer (DiT)** architecture to generate State-of-the-Art textures from the DTD dataset while keeping VRAM usage extremely low.\n",
    "\n",
    "### Why this works so well:\n",
    "1. **Pre-trained VAE:** We freeze a massive pre-trained Autoencoder (from Stable Diffusion) to perfectly handle the high-frequency pixel details. It compresses our 64x64 images into tiny 8x8 grids, saving 90% memory.\n",
    "2. **Diffusion Transformer (DiT):** We run a Transformer network (instead of a U-Net) strictly over the tiny 8x8 grid. Transformers are brilliant at global coherence (making sure a pattern aligns everywhere).\n",
    "3. **Bulletproof Stability:** The training loop includes AdamW, explicit NaN-skipping, and clamped variance math to absolutely guarantee zero crashes."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "# Install necessary HuggingFace libraries if they are missing\n",
    "try:\n",
    "    import diffusers\n",
    "except ImportError:\n",
    "    !pip install -q diffusers transformers accelerate"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "import os\n",
    "import math\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "import torchvision\n",
    "import torchvision.transforms as T\n",
    "from torch.utils.data import DataLoader\n",
    "import torchvision.utils as vutils\n",
    "from tqdm.auto import tqdm\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from diffusers import AutoencoderKL\n",
    "\n",
    "# Configuration\n",
    "BATCH_SIZE = 32\n",
    "IMAGE_SIZE = 64\n",
    "EPOCHS = 100\n",
    "LR = 2e-4\n",
    "DEVICE = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
    "DATA_DIR = \"./data\"\n",
    "OUTPUT_DIR = \"./latent_dit_outputs\"\n",
    "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
    "os.makedirs(DATA_DIR, exist_ok=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "# Dataset and DataLoader (Zero Multiprocessing Threads = Zero Crashes)\n",
    "transform = T.Compose([\n",
    "    T.Resize((IMAGE_SIZE, IMAGE_SIZE)),\n",
    "    T.RandomHorizontalFlip(),\n",
    "    T.RandomVerticalFlip(),\n",
    "    T.ToTensor(),\n",
    "    T.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]) # Normalize to [-1, 1]\n",
    "])\n",
    "\n",
    "print(\"Downloading/Loading DTD Dataset...\")\n",
    "dataset = torchvision.datasets.DTD(root=DATA_DIR, split='train', download=True, transform=transform)\n",
    "dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0, pin_memory=False, drop_last=True)\n",
    "print(f\"Dataset loaded: {len(dataset)} images.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "# 1. Load Pre-trained VAE (Frozen to save VRAM)\n",
    "print(\"Downloading pre-trained VAE (Stability AI)...\")\n",
    "vae = AutoencoderKL.from_pretrained(\"stabilityai/sd-vae-ft-mse\").to(DEVICE)\n",
    "vae.eval() # Inference only\n",
    "for param in vae.parameters():\n",
    "    param.requires_grad = False\n",
    "    \n",
    "VAE_SCALE_FACTOR = 0.18215 # Standard Stable Diffusion scaling factor for latents\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "# 2. Diffusion Transformer (DiT) Architecture\n",
    "class SinusoidalPositionEmbeddings(nn.Module):\n",
    "    def __init__(self, dim: int):\n",
    "        super().__init__()\n",
    "        self.dim = dim\n",
    "\n",
    "    def forward(self, time: torch.Tensor):\n",
    "        device = time.device\n",
    "        half_dim = self.dim // 2\n",
    "        embeddings = math.log(10000) / (half_dim - 1)\n",
    "        embeddings = torch.exp(torch.arange(half_dim, device=device) * -embeddings)\n",
    "        embeddings = time[:, None] * embeddings[None, :]\n",
    "        embeddings = torch.cat((embeddings.sin(), embeddings.cos()), dim=-1)\n",
    "        return embeddings\n",
    "\n",
    "class AdaLN(nn.Module):\n",
    "    \"\"\"Adaptive Layer Normalization (injects time-step info into Transformer blocks)\"\"\"\n",
    "    def __init__(self, dim: int):\n",
    "        super().__init__()\n",
    "        self.norm = nn.LayerNorm(dim, elementwise_affine=False)\n",
    "        self.linear = nn.Linear(dim, 2 * dim)\n",
    "        \n",
    "    def forward(self, x, c):\n",
    "        shift, scale = self.linear(c).chunk(2, dim=-1)\n",
    "        return self.norm(x) * (1 + scale.unsqueeze(1)) + shift.unsqueeze(1)\n",
    "\n",
    "class DiTBlock(nn.Module):\n",
    "    def __init__(self, dim: int, n_heads: int):\n",
    "        super().__init__()\n",
    "        self.norm1 = AdaLN(dim)\n",
    "        self.attn = nn.MultiheadAttention(dim, n_heads, batch_first=True)\n",
    "        self.norm2 = AdaLN(dim)\n",
    "        self.mlp = nn.Sequential(\n",
    "            nn.Linear(dim, dim * 4),\n",
    "            nn.GELU(),\n",
    "            nn.Linear(dim * 4, dim)\n",
    "        )\n",
    "        \n",
    "    def forward(self, x, c):\n",
    "        nx = self.norm1(x, c)\n",
    "        x = x + self.attn(nx, nx, nx)[0]\n",
    "        nx = self.norm2(x, c)\n",
    "        x = x + self.mlp(nx)\n",
    "        return x\n",
    "\n",
    "class LatentDiT(nn.Module):\n",
    "    \"\"\"Diffusion Transformer operating on the 8x8 compressed latent space.\"\"\"\n",
    "    def __init__(self, in_channels=4, embed_dim=256, depth=6, n_heads=8, latent_size=8):\n",
    "        super().__init__()\n",
    "        # Linear patch embedding (treats each 1x1 latent pixel as a token)\n",
    "        self.patch_embed = nn.Conv2d(in_channels, embed_dim, kernel_size=1)\n",
    "        self.pos_embed = nn.Parameter(torch.zeros(1, latent_size * latent_size, embed_dim))\n",
    "        \n",
    "        # Time embedding MLP\n",
    "        self.time_mlp = nn.Sequential(\n",
    "            SinusoidalPositionEmbeddings(embed_dim),\n",
    "            nn.Linear(embed_dim, embed_dim),\n",
    "            nn.GELU(),\n",
    "            nn.Linear(embed_dim, embed_dim)\n",
    "        )\n",
    "        \n",
    "        self.blocks = nn.ModuleList([DiTBlock(embed_dim, n_heads) for _ in range(depth)])\n",
    "        self.norm_out = AdaLN(embed_dim)\n",
    "        self.head = nn.Linear(embed_dim, in_channels)\n",
    "\n",
    "    def forward(self, x, time):\n",
    "        B, C, H, W = x.shape\n",
    "        \n",
    "        # Flatten 8x8 grid into sequence of 64 tokens\n",
    "        x = self.patch_embed(x).flatten(2).transpose(1, 2) # [B, 64, D]\n",
    "        x = x + self.pos_embed\n",
    "        \n",
    "        c = self.time_mlp(time)\n",
    "        for block in self.blocks:\n",
    "            x = block(x, c)\n",
    "            \n",
    "        x = self.norm_out(x, c)\n",
    "        x = self.head(x) # [B, 64, 4]\n",
    "        \n",
    "        # Reshape back to 8x8 grid\n",
    "        x = x.transpose(1, 2).reshape(B, C, H, W)\n",
    "        return x\n",
    "\n",
    "class StableDDPM(nn.Module):\n",
    "    def __init__(self, model: LatentDiT, timesteps: int = 1000):\n",
    "        super().__init__()\n",
    "        self.model = model\n",
    "        self.timesteps = timesteps\n",
    "\n",
    "        beta = torch.linspace(0.0001, 0.02, timesteps)\n",
    "        alpha = 1. - beta\n",
    "        alpha_hat = torch.cumprod(alpha, dim=0)\n",
    "\n",
    "        self.register_buffer(\"beta\", beta)\n",
    "        self.register_buffer(\"alpha\", alpha)\n",
    "        self.register_buffer(\"alpha_hat\", alpha_hat)\n",
    "\n",
    "    def forward(self, x):\n",
    "        device = x.device\n",
    "        t = torch.randint(0, self.timesteps, (x.shape[0],), device=device).long()\n",
    "        noise = torch.randn_like(x)\n",
    "\n",
    "        alpha_hat_t = self.alpha_hat[t].view(-1, 1, 1, 1)\n",
    "        \n",
    "        # CRITICAL FIX for NaN issues\n",
    "        alpha_hat_t = torch.clamp(alpha_hat_t, max=0.9999)\n",
    "        one_minus_alpha_hat_t = torch.clamp(1.0 - alpha_hat_t, min=1e-5)\n",
    "        \n",
    "        x_noisy = torch.sqrt(alpha_hat_t) * x + torch.sqrt(one_minus_alpha_hat_t) * noise\n",
    "        pred_noise = self.model(x_noisy, t)\n",
    "        return F.mse_loss(pred_noise, noise)\n",
    "\n",
    "    @torch.no_grad()\n",
    "    def sample(self, num_samples, vae, latent_size=8, channels=4, device=\"cuda\"):\n",
    "        \"\"\"Generates samples by running diffusion in latent space, then decoding via VAE.\"\"\"\n",
    "        # 1. Start with pure noise in LATENT space (8x8x4)\n",
    "        x = torch.randn((num_samples, channels, latent_size, latent_size), device=device)\n",
    "        \n",
    "        for i in tqdm(reversed(range(self.timesteps)), desc=\"Latent Sampling\", leave=False, total=self.timesteps):\n",
    "            t = torch.full((num_samples,), i, device=device, dtype=torch.long)\n",
    "            pred_noise = self.model(x, t)\n",
    "            \n",
    "            alpha_t = self.alpha[t].view(-1, 1, 1, 1)\n",
    "            alpha_hat_t = self.alpha_hat[t].view(-1, 1, 1, 1)\n",
    "            beta_t = self.beta[t].view(-1, 1, 1, 1)\n",
    "            \n",
    "            one_minus_alpha_hat_t = torch.clamp(1.0 - alpha_hat_t, min=1e-5)\n",
    "\n",
    "            noise = torch.randn_like(x) if i > 0 else torch.zeros_like(x)\n",
    "            x = (1 / torch.sqrt(alpha_t)) * (x - ((1 - alpha_t) / torch.sqrt(one_minus_alpha_hat_t)) * pred_noise) + torch.sqrt(beta_t) * noise\n",
    "\n",
    "        # 2. Decode the latents back into 64x64 pixel images using the VAE\n",
    "        x = x / VAE_SCALE_FACTOR\n",
    "        decoded_images = vae.decode(x).sample\n",
    "        \n",
    "        # 3. Denormalize pixel images from [-1, 1] to [0, 1]\n",
    "        decoded_images = (decoded_images.clamp(-1, 1) + 1) / 2\n",
    "        return decoded_images\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "# Initialize Latent DiT Model\n",
    "# 64x64 image -> VAE factor 8 -> 8x8 latent grid\n",
    "dit = LatentDiT(in_channels=4, embed_dim=256, depth=6, n_heads=8, latent_size=8).to(DEVICE)\n",
    "model = StableDDPM(dit, timesteps=1000).to(DEVICE)\n",
    "\n",
    "optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)\n",
    "scaler = torch.cuda.amp.GradScaler(enabled=True)\n",
    "\n",
    "print(f\"Starting Latent DiT training on {DEVICE}...\")\n",
    "\n",
    "for epoch in range(1, EPOCHS + 1):\n",
    "    model.train()\n",
    "    total_loss = 0.0\n",
    "    valid_batches = 0\n",
    "    \n",
    "    pbar = tqdm(dataloader, desc=f\"Epoch {epoch}/{EPOCHS}\")\n",
    "    for batch in pbar:\n",
    "        images, _ = batch\n",
    "        images = images.to(DEVICE)\n",
    "        \n",
    "        optimizer.zero_grad(set_to_none=True)\n",
    "        \n",
    "        # -- LATENT COMPRESSION STEP --\n",
    "        with torch.no_grad():\n",
    "            # Compress raw 64x64x3 pixel images into 8x8x4 latent representations\n",
    "            latents = vae.encode(images).latent_dist.sample()\n",
    "            latents = latents * VAE_SCALE_FACTOR\n",
    "            \n",
    "        # -- DIFFUSION TRANSFORMER STEP --\n",
    "        with torch.cuda.amp.autocast(enabled=True):\n",
    "            loss = model(latents)\n",
    "            \n",
    "        # Safe NaN guard\n",
    "        if not math.isfinite(loss.item()):\n",
    "            print(f\"\\nWARNING: NaN loss detected at epoch {epoch}. Skipping batch.\")\n",
    "            continue\n",
    "            \n",
    "        scaler.scale(loss).backward()\n",
    "        \n",
    "        # Strict Gradient Clipping\n",
    "        scaler.unscale_(optimizer)\n",
    "        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)\n",
    "        \n",
    "        scaler.step(optimizer)\n",
    "        scaler.update()\n",
    "        \n",
    "        total_loss += loss.item()\n",
    "        valid_batches += 1\n",
    "        pbar.set_postfix({\"loss\": f\"{loss.item():.4f}\"})\n",
    "        \n",
    "    avg_loss = total_loss / max(1, valid_batches)\n",
    "    print(f\"Epoch {epoch} | Average Loss: {avg_loss:.4f}\")\n",
    "    \n",
    "    torch.save({\n",
    "        \"epoch\": epoch,\n",
    "        \"model_state_dict\": model.state_dict(),\n",
    "        \"optimizer_state_dict\": optimizer.state_dict(),\n",
    "        \"loss\": avg_loss\n",
    "    }, os.path.join(OUTPUT_DIR, \"latent_dit_latest.pt\"))\n",
    "    \n",
    "    if epoch % 5 == 0 or epoch == 1:\n",
    "        model.eval()\n",
    "        print(f\"Generating Latent DiT samples for epoch {epoch}...\")\n",
    "        with torch.no_grad():\n",
    "            # We pass the frozen VAE into the sample function so it can decode the latents back to pixels\n",
    "            samples = model.sample(num_samples=16, vae=vae, latent_size=8, channels=4, device=DEVICE)\n",
    "            grid = vutils.make_grid(samples, nrow=4, padding=2, normalize=False)\n",
    "            \n",
    "            sample_path = os.path.join(OUTPUT_DIR, f\"latent_dit_epoch_{epoch:03d}.png\")\n",
    "            vutils.save_image(samples, sample_path, nrow=4, padding=2, normalize=False)\n",
    "            \n",
    "            plt.figure(figsize=(8, 8))\n",
    "            plt.axis(\"off\")\n",
    "            plt.title(f\"Latent DiT Epoch {epoch} Samples\")\n",
    "            plt.imshow(np.transpose(grid.cpu().numpy(), (1, 2, 0)))\n",
    "            plt.show()\n",
    "\n",
    "print(\"Latent DiT Training Complete!\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("latent_dit_training.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)
